#+TITLE: SSH tutorial (UNDER DEVELOPMENT)
#+AUTHOR: Konrad U. Förstner

This work by Konrad Förstner is licensed under a [[https://creativecommons.org/licenses/by/4.0/][Creative Commons
Attribution 4.0 International License]].

Version: 0.1

** Introduction

The tool [[https://en.wikipedia.org/wiki/Secure_Shell][SSH]] (Secure Shell) can be used to connect to another computer
and execute programs there. The remote machine is often a server that
for example offer more computational power than you laptop. The most
widely used implemenation of SSH is [[http://www.openssh.com/][OpenSSH]].

** Basic usage

In order to connect to the remote machine you need to have an account
on it. In the following examples we assume that you have an account
called =alice= and a remote machine called =bobs_server= (Your name is
not Alice and you don't know any Bob? [[https://en.wikipedia.org/wiki/Alice_and_Bob][Read this]] to understand the
choice of names).

You can connect to a remote machine and have an interactive session by
calling ssh like this (don't copy the =$= sign):

#+BEGIN_EXAMPLE
    $ ssh <your_username>@<server_name_or_ip>
#+END_EXAMPLE

In our example this would be

#+BEGIN_EXAMPLE
    $ ssh alice@bobs_server
#+END_EXAMPLE

SSH will presend you the host finger print

#+BEGIN_EXAMPLE
    Host key fingerprint is SHA256:ZwDBE5pV7SCqTXrHYzBChkhn3Nkx6cvvF9StX+W25No
    +---[ECDSA 256]---+
    |oo.o..B*+.       |
    |o =. *++o .      |
    | o  o..o.o  . .  |
    |  . =  . ... . ..|
    |   * +. S +   ...|
    |  o o =o o . . .+|
    |   . o ..   . +.o|
    |         . .  .+ |
    |        ...  ..E |
    +----[SHA256]-----+
#+END_EXAMPLE

The first time your are connting to a remove machine you will be asked
to continue. Please type =yes= and press Enter.

#+BEGIN_EXAMPLE
    Are you sure you want to continue connecting (yes/no)?
    Warning: Permanently added 'hawaii' (ECDSA) to the list of known hosts
#+END_EXAMPLE

Then will be asked for your password.

#+BEGIN_EXAMPLE
    alice@bobs_server's password:
#+END_EXAMPLE

Please enter your password and press Enter. Now you should have an
interactive shell session on the remote machine. You prompt might
indicate this but you can use =hostname= to make that you are on the
remote machine.

#+BEGIN_EXAMPLE
    $ hostname
    bobs_server
#+END_EXAMPLE

Now you can run commandline tools like on your local machine. If the
server is adequately configured you can even run tools with a
graphical interface (GUI) using so called X11-forwarding. For this
connect with ssh using the -X flag.

#+BEGIN_EXAMPLE
    $ ssh -X alice@bobs_server
#+END_EXAMPLE

You can also run SSH non-interactively by calling it with a command to
execute:

#+BEGIN_EXAMPLE
    $ ssh <your_username>@<server_name_or_ip> <command>
#+END_EXAMPLE

#+BEGIN_EXAMPLE
    exit
#+END_EXAMPLE

Example:

#+BEGIN_EXAMPLE
    $ ssh alice@bobs_server ls
#+END_EXAMPLE

This will list the file in the home directory of the remote
machine. You will not have an interactive session on that machine but
will stay in the session of you local machine after the file list is
returned.

** Copying files with scp

Basic

#+BEGIN_EXAMPLE
    $ scp <source> <target>
#+END_EXAMPLE

Folder

#+BEGIN_EXAMPLE
    $ scp -r <source> <target>
#+END_EXAMPLE

Using compression

#+BEGIN_EXAMPLE
    $ scp -C <source> <target>
#+END_EXAMPLE

Using compression when sending

#+BEGIN_EXAMPLE
    $ scp -rC <source> <target>
#+END_EXAMPLE

Examples. Be aware that =~/= represent your home directory on
GNU/Linux and the different BSD this is usually
=/home/your_username=. On OS X this is =/Users/your_username=. 

This will copy the file =my_local_big_file.txt= from your local
machine into your home directory of the remote machine.

#+BEGIN_EXAMPLE
    $ scp my_local_big_file.txt alice@bobs_server:~/
#+END_EXAMPLE

The following command will send the file to the server and rename it
to =my_remote_big_file.txt=.

#+BEGIN_EXAMPLE
    $ scp my_local_big_file.txt alice@bobs_server:~/my_remote_big_file.txt
#+END_EXAMPLE

Sure you can use scp to copy from the server to you local machine:

#+BEGIN_EXAMPLE
    $ scp alice@bobs_server:/data/my_local_big_file.txt .
#+END_EXAMPLE

** Configure SSH

While you are now capable of working on the remote machine you have to
type a lot to connect to it. /Laziness is virtue/ - in the following we
will make working with SSH more convinient and reduce the need of
typing.

#+BEGIN_EXAMPLE
    $ mkdir -p ~/.ssh
#+END_EXAMPLE

Make it unaccessible by other users:

#+BEGIN_EXAMPLE
    $ chmod -R go-rwx ~/.ssh
#+END_EXAMPLE

Open

#+BEGIN_EXAMPLE
    $ touch ~/.ssh/config
#+END_EXAMPLE

Add

#+BEGIN_EXAMPLE
    Host bobs
      User alice
      HostName bobs_server
#+END_EXAMPLE

Now you can connect to the server simply by calling

#+BEGIN_EXAMPLE
    $ ssh bobs
#+END_EXAMPLE

or copy files with

#+BEGIN_EXAMPLE
    $ scp my_file.txt bobs:~/
#+END_EXAMPLE

** Using SSH keys

Currently you have to type your password everytime you connect to the
remote machine. In order to avoid that we will generate once a so called
SSH key pair. A private key will be stored at you local machine and
should be keep private! The has to be put on the server and can be
liberately given away (e.g. a system administrator might ask you for the
public key in order to give you access to a remote machine without any
password). More details regarding this public/private key approach can
be found
[[https://en.wikipedia.org/wiki/Public-key_cryptography][here]].

Generate a key pair on your local machine. We use =-b 4096= in order to
generate a stronger key than with the default settings and =-N ""= to
set no passphrase for the key. This can take a while.

#+BEGIN_EXAMPLE
    $ ssh-keygen -b 4096 -N ""
#+END_EXAMPLE

During the procedure you will be asked for the file name of the key
file. Use the default by pressing Enter:

#+BEGIN_EXAMPLE
    Generating public/private rsa key pair.
    Enter file in which to save the key (/home/your_local_user_name/.ssh/id_rsa):
    Your identification has been saved in /home/your_local_user_name/.ssh/id_rsa.
    Your public key has been saved in /home/your_local_user_name/.ssh/id_rsa.pub.
    The key fingerprint is:
    0b:5c:b3:e8:51:d2:0e:3b:b8:cc:6d:97:4d:1d:e7:f0 your_local_user_name@your_local_machine
    The key's randomart image is:
    +--[ RSA 4096]----+
    |                 |
    |       .         |
    |      o =   o .  |
    |     o O o . *   |
    |    . B S . . E  |
    |   o + + =       |
    |    + + + .      |
    |     . .         |
    |                 |
    +-----------------+
#+END_EXAMPLE

As =ssh-keygen= reported we have now two files:

-  Your private key file =/home/your_local_user_name/.ssh/id_rsa=
-  Your public key file =/home/your_local_user_name/.ssh/id_rsa.pub=

Those are just plain test files and you can have a look at them using
=cat= or =less=:

#+BEGIN_EXAMPLE
    $ cat ~/.ssh/id_rsa
    $ cat ~/.ssh/id_rsa.pub
#+END_EXAMPLE

Set up .ssh on the server

#+BEGIN_EXAMPLE
    $ ssh alice@bobs_server "mkdir -p ~/.ssh"
#+END_EXAMPLE

Add the public key to the file (as you can see you can even pipe
commands into SSH):

#+BEGIN_EXAMPLE
    $ cat ~/.ssh/*.pub | ssh alice@bobs_server 'cat >> ~/.ssh/authorized_keys'
#+END_EXAMPLE

Add to local key-chain:

#+BEGIN_EXAMPLE
     $ ssh-add ~/.ssh/id_rsa
#+END_EXAMPLE

** Persistent session with tmux

Alternatives:

-  nohub
-  screen

The terminal multiplexer [[https://tmux.github.io/][tmux]]

Start

#+BEGIN_EXAMPLE
     $ tmux
#+END_EXAMPLE

List sessions:

#+BEGIN_EXAMPLE
     $ tmux list-sessions
#+END_EXAMPLE

Reconnect

#+BEGIN_EXAMPLE
    $ tmux attach
#+END_EXAMPLE

or simply

#+BEGIN_EXAMPLE
    $ tmux a
#+END_EXAMPLE

Important keys:

-  =Ctr-b c= - new window
-  =Ctr-b ,= - rename window
-  =Ctr-b x= - close window
-  =Ctr-b \<NUMBER\>= - go to window with
-  =Ctr-b [= - switch scrolliing mode; use =q= to quit

List keys

#+BEGIN_EXAMPLE
    $ tmux list-keys
#+END_EXAMPLE

List commands

#+BEGIN_EXAMPLE
    $ tmux list-commands
#+END_EXAMPLE

Configure =~/.tmux.conf=:

#+BEGIN_EXAMPLE
    # Change prefix to Control + o
    set -g prefix C-o

    # Increase history length
    set -g history-limit 1000
#+END_EXAMPLE

** Further topics

-  Mosh (mobile shell) - https://mosh.mit.edu/ - more robust and
   responsive alternative to SSH.
-  SSHFS https://en.wikipedia.org/wiki/SSHFS https://osxfuse.github.io/
   https://github.com/osxfuse/osxfuse/wiki/SSHFS

mkdir -p server\_folder sshf alice@bobs\_server:/home/alice
server\_folder umount server\_folder
