#+TITLE: Machine Learning

** Links 
  
- [[https://www.openml.org/][OpenML]]
- [[https://blog.floydhub.com/coding-the-history-of-deep-learning/][Coding the History of Deep Learning]]

** Python libraries
- [[http://scikit-learn.org/][scikit-learn]] - Numorous ML methods with a cosistent interface
- [[http://pytorch.org/][pytorch]] - Tensors and Neural Networks 

** Articles/Reviews

- Libbrecht MW, Noble WS. Machine learning applications in genetics
  and genomics. Nat Rev Genet. 2015 Jun;16(6):321-32,
  https://dx.doi.org/10.1038/nrg3920,
  ([[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5204302/][Free version on PubMedCentral]])

- Yip KY, Cheng C, Gerstein M. Machine learning and genome annotation:
  a match meant to be? Genome Biol. 2013 May
  29;14(5):205. https://dx.doi.org/10.1186/gb-2013-14-5-205.

- Noble WS. What is a support vector machine? Nat Biotechnol. 2006
  Dec;24(12):1565-7. https://doi.org/10.1038/nbt1206-1565

- Ben-Hur A, Ong CS, Sonnenburg S, Schölkopf B, Rätsch G. Support
  vector machines and kernels for computational biology. PLoS Comput
  Biol. 2008 Oct;4(10):e1000173. https://doi.org/10.1371/journal.pcbi.1000173

- Kingsford C, Salzberg SL. What are decision trees? Nat
  Biotechnol. 2008 Sep;26(9):1011-3.
  https://doi.org/10.1038/nbt0908-1011

** Books

-  [[http://shop.oreilly.com/product/0636920030515.do][Introduction to Machine Learning with Python - A Guide for Data
   Scientists]], Andreas C. Müller, Sarah Guido, O'Reilly Media, 2016,
   ISBN-13: 978-1449369415

-  [[https://mitpress.mit.edu/books/machine-learning-0][Machine Learning - A Probabilistic Perspective]], Kevin P. Murphy,
   2012, ISBN: 9780262018029

   

